#
# Basic services
#

parameters:

    fbfb.form.type.slider.class: FlorianBelhomme\Bundle\FoundationBundle\Form\Type\SliderType

services:

    fbfb.form.type.slider:
            class: %fbfb.form.type.slider.class%
            tags:
                - { name: form.type, alias: slider }