parameters:

    fbfb.form.type.slider.class: FlorianBelhomme\Bundle\FoundationBundle\Form\Type\SliderType
    fbfb.form.type.switch.class: FlorianBelhomme\Bundle\FoundationBundle\Form\Type\SwitchType

services:

    fbfb.form.type.slider:
            class: %fbfb.form.type.slider.class%
            tags:
                - { name: form.type, alias: slider }

    fbfb.form.type.switch:
            class: %fbfb.form.type.switch.class%
            tags:
                - { name: form.type, alias: switch }
